config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'

  get '/about', to: 'about#index'
 
  get '/auth/google_oauth2/callback', to: 'users#create'

  get '/satellite', to: 'satellites#show'

  resource :users do
    get '/dashboard', to: "users#show"
    get '/discover', to: "discover#index"
  end
  
  resources :messages, only: [:show, :new]

  post 'messages/create', to: 'messages#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index

  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in_user, :remote_ip, :lat_long 
# :nocov:
    def remote_ip
      if request.remote_ip == '127.0.0.1' || request.remote_ip == '::1'
        #hard coded as backup New York City
        lat_long('161.185.160.93')
      else
        lat_long(request.remote_ip)
      end
    end

    def lat_long(ip)
      location = Geocoder.search(ip)
      lat_long = location.first.coordinates
      @lat = lat_long[0]
      @long = lat_long[1]
    end 

    def logged_in_user
        unless session[:user_id]
            flash[:alert] = 'Please log in to view this page'
            redirect_to '/'
        end
    end
# :nocov:
end

app/controllers/discover_controller.rb
class DiscoverController < ApplicationController
  before_action :remote_ip, :logged_in_user

  def index
    @satellites = SatelliteFacade.above_satellites(@lat, @long)
    @message_count_arrays = []
    @satellites.each do |satellite|
      @message_count_arrays << MessageFacade.get_message_count(satellite.satid) 
    end 
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :logged_in_user, :remote_ip

  def show 
    @message = MessageFacade.get_message(params[:id])
    if @message != 404
      sat_norad_id = SatelliteFacade.get_norad_id(@message.satellite_id)[:data][:attributes][:norad_id]
      @satellite = SatelliteFacade.get_satellite_position(sat_norad_id)
      @map_url = MapMaker.new(@lat,@long,@satellite.sat_lat,@satellite.sat_lng,@message.start_lat,@message.start_lng).result_url
    end 
  end

  def new 
    @sat_id = params[:sat_id]
  end 

  def create 
    if params[:message] != ""
      SatelliteFacade.create_user_satellite(params[:sat_id], session[:user_id])
      MessageFacade.create_message(@lat, @long, params[:message], params[:sat_id])
      redirect_to '/users/dashboard'
      # flash[:success] = "Message sent!"    
    else 
      redirect_to '/messages/new'
      flash[:error] = "Your message can't be blank!"
    end 
  end 

end

app/controllers/satellites_controller.rb
class SatellitesController < ApplicationController
  before_action :logged_in_user, :remote_ip, 

  def show
    @sat_id = SatelliteFacade.create_satellite(params[:sat_id])
    @satellite = SatelliteFacade.get_satellite_position(params[:sat_id])
    if @satellite != 404 
      @visibility = SatelliteFacade.get_satellite_visibility(params[:sat_id], @lat, @long)
      @weather_forecasts = WeatherFacade.get_weather_forecast(@lat, @long)
      @messages = SatelliteFacade.get_sat_message_id(@sat_id)
      @map_url = SatMapMaker.new(@satellite.sat_lat, @satellite.sat_lng).result_url
    end 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show]
  before_action :remote_ip

  def create
    user_info = request.env['omniauth.auth']
    if user_info['credentials']['token'].present?
      @user = UserFacade.find_or_create_user(user_info['info']['name'], user_info['info']['email'])
      set_session(@user)
      redirect_to dashboard_users_path
    else
      redirect_to root_path
      flash[:error] = 'Invalid Credentials'
    end
  end

  def show  
    @satellites = SatelliteFacade.get_user_satellites(session[:user_id])
    @visible_times = @satellites.map do |satellite|
      SatelliteFacade.get_satellite_visibility(satellite.id, @lat, @long)
    end.flatten  
    @visible_times.compact!
    @message_count = @satellites.map do |satellite|
      SatelliteFacade.get_sat_message_id(satellite.id)
    end.flatten
    @weather_forecasts = WeatherFacade.get_weather_forecast(@lat, @long)
  end

  private

  def set_session(user)
    session[:user_id] = user.id
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<!DOCTYPE html>
<html lang ="en">
<head>
  <title>Message from the Stars</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <script>
    function myFunction() {
      var popup = document.getElementById("myPopup");
      popup.classList.toggle("show");
    }
  </script>
  <%= render partial: "shared/nav-hamburger" %>
</head>
<body>
<div class="guide">
<div class="image" style='width:50%'>
    <h2>
      Getting Started
    </h2>

    <p>
      If this is your first time here, your "Tracked Satellites" on the dashboard is going to be empty - let's fix that! 
    </p>

    <p>
      To get started, let's click on "Scan the Skies" on the navigation bar at the top of your screen, and you should see a page that looks something like this:
    </p>

    <%= image_tag "scan_page_shot.jpg", style: 'width:100%;border 2px solid black'%>
    
    <p>
      This 'scan' page uses your current location, and determines what satellites are above you at this exact moment in time (more specifically, within a 15 degree angle above you).
    </p>

    <p>
      Let's see some more information about this satellite zipping by above you. Click on "View Satellite's Info" button. 
    </p>

    <%= image_tag "scan_circled_link.jpg", style: 'width:100%;border 2px solid black'%>

    <p>
      After clicking on a "more info" button, we are taken to a page showing us a couple of interesting pieces of information:
    </p>

    <ol id="info-list">
      <li>
        A map with this satellite's current location.
      </li>

      <li>
        A 10 day 'visibility' forecast
      </li>

      <li>
        An option to "Cast a New Message"
      </li>

      <li>
        Links to all of the messages attached to this satellite (if any have been attached).
      </li>
    </ol>

    <%= image_tag "circled_sat_show.jpg", style: 'width:100%;border 2px solid black'%>
    
    <p>
      Let's say you scan the skies and you see an interesting satellite, like the International Space Station, or a piece of rocket debris from the 1960s, and you want to send out a message for anyone else lucky enough to see it when they scan their skies.  
    </p>

    <p>
      Click on the "Cast a New Message" button, and you'll be taken to a page to write your message.
    </p>

    <%= image_tag "circled_cast_message.jpg", style: 'width:100%;border 2px solid black'%>
  
    <p>
      Let's type a nice note, and click "Send Message". Our message is now latched on to the International Space Station!
    </p>

    <%= image_tag "circled_new_message.jpg", style: 'width:100%;border 2px solid black'%>

    <p>
      Now, let's say it is a few days later and you remember that you've attached a message to something zipping around the earth every 90 minutes, and you'd like to know where it is, or if anyone else has added a message. So, let's go back to our Control Center by clicking the link on the navigation bar. 
    </p>

    <%= image_tag "control_center_link.jpg", style: 'width:100%;border 2px solid black'%>

    <p>
      Now, the satellite that you've attached your message to will be part of your "Tracked Satellites", so you can click to view information, no matter if it is above you or not! Let's click that link to view more information, and we're back on the page for that satellite, and we can see that your message is there, along with any other messages other users have attached to this satellite!
    </p>

    <%= image_tag "circled_control_center.jpg", style: 'width:100%;border 2px solid black'%>

    <p>
      Let's click on one of these other messages and learn more. 
    </p>

    <%= image_tag "circled_message_link.jpg", style: 'width:100%;border 2px solid black'%>

    <p>
      On this page, we can see:
    </p>

    <ol id="message-show-items">
      <li>
        The message contents - the actual note that was attached. 
      </li>

      <li>
        A map marking your location, the location this message was sent from, and where this message is right now.
      </li>

      <li>
        Information about when this message was sent, how many times it has traveled around the world, and how far it has traveled since it was launched. 
      </li>
    </ol>

    <%= image_tag "circled_message_show.jpg", style: 'width:100%;border 2px solid black'%>

    <p>
      As you send more messages, the number of satellites that you are tracking will grow, and the chances of seeing messages in response or alongside yours on the same satellite will grow!
    </p>

    <div id="faqs">
      <h2> 
        FAQs
      </h2>

      <h3>
        How do we determine 'visibility'?
      </h3>

      <p>
        Similar to 'scanning the skies', these visible passes are based on your location while using the app. A 'visible pass' of a satellite occurs when a satellite enters a viewer's local horizon (the portion of the sky you can see from your location), during a time when the satellite is not in Earth's shadow (so it can reflect sunlight), and during a time when the sky in your area *might* be dark enough to see the light reflected off of the satellite against a dark background.
      <p>

      <p>
        A 'visual pass' calculation does not, however, account for your local weather. So for your convenience, you can hover over any visual pass times on this page to see a simplified weather report for your location at the time of this pass will occur. 
      <p>
      
      <p>
        If you find a 'clear' report for an upcoming visual pass and are in an area with low light pollution, get outside and look up! You might be able to see this satellite zipping overhead at 17,500 MPH!
      </p>

      <h3>
        Why do I see lots of visual passes coming up?
      </h3>

      <p>
        Satellites in LEO (low earth orbit), like the International Space Station, travel around the world in about 90 minutes at around 17,500 miles per hour! So, the exact collection of satellites you see on this page will be different every time you load it and start a new scan, as some of these LEO satellites will orbit out of your area and others will orbit into your area very quickly! If you are in New York City and see a LEO satellite above you, it could be as far away as London within 15 minutes, and then back over you again a little over an hour after that.
      </p>

      <h3>
        Why are some satellites *always* on this page?
      </h3>

      <p>
        Satellites in *geosynchronous* orbit, like many weather satellites, orbit at the exact same speed as the Earth, meaning they will remain above the same location at all times. If you are in the area of one of these satellites, it will not orbit in and out of your area, but will always show up when you scan the skies in the same location!
      <p>

      <p>
        For more information on these orbits and others, check out the European Space Agency's great page explaining different types of orbits <%= link_to "at this link", "https://www.esa.int/Enabling_Support/Space_Transportation/Types_of_orbits#orbits"%>.
      </p>

    </div>
  </div>

  <div class="project-info">
    <h2>
      Project Information
    </h2>

    <div id="repo-links">
      <h3>
        Repository Links
      </h3>
      <div class="fe-repo-link"> 
        <%= link_to "Front-End Repository", "https://github.com/messages-from-the-stars/messages-from-the-stars-fe"%>
      <div>
      <div class="be-repo-link">
        <%= link_to "Back-End Repository", "https://github.com/messages-from-the-stars/messages-from-the-stars-be"%>
      </div>
    </div>

    <div id="contributors">
      <h3>
        Contributors (in reverse alphabetical order):
      </h3>

      <div class="contributor-1">
        <%= link_to "@tig-o", "https://github.com/tig-o"%>
      </div>

      <div class="contributor-2">
        <%= link_to "@philmarcu", "https://github.com/philmarcu"%>
      </div>

      <div class="contributor-3">
        <%= link_to "@mikekoul", "https://github.com/mikekoul"%>
      </div>

      <div class="contributor-4">
        <%= link_to "@jonathanmpope", "https://github.com/jonathanmpope"%>
      </div>

      <div class="contributor-5">
        <%= link_to "@alepbloyd", "https://github.com/alepbloyd"%>
      </div>
    </div>
</div>
</div>
</body>
</html>

app/views/discover/index.html.erb
<!DOCTYPE html>
<html lang ="en">
<head>
  <title>Messages from the Stars</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <%= render partial: "shared/nav-hamburger" %>
</head>
<body>
<div class="bg_discover">

  <div class="discover_container_header">
    <p>Scan Results</p>
  </div> 
  <div class="discover_container_subheader">
    <p>Click on Info to explore the object above you and create or view messages</p>
  </div>
    <% @satellites.each_with_index do |satellite, index| %>
  <div id="satellites<%= index %>">

    <div class="col-md-6" >
      <p>Name: <%= satellite.satname %> ID: <%= satellite.satid  %><p>
      <p>Launched on: <%= satellite.launch_date %><p>
      <p><%= button_to "View #{satellite.satname}'s Info", '/satellite', params: {:sat_id => satellite.satid}, method: :get, local: true, class: 'discover-button' %><p>
      <% x = 0 %> 
      <% @message_count_arrays.each do |array| %>
        <% if array[0] == satellite.satid %>
          <% x = array[1] %> 
        <% end %>
      <% end %>
      <p><%= x %> Messages<p>
    </div>

  <% end %>
  </div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessagesFromTheStarsFe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <center><%= content_tag :div, msg, class: name %><center>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/messages/new.html.erb
<!DOCTYPE html>
<html lang ="en">
<head>
  <title>Messages from the Stars</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <%= render partial: "shared/nav-hamburger" %>
</head>

<body>
<div class="bg_new_message">
    <p class="py-5 text-center"></p>

  <div class="new_message_container">
      <p>Cast a New Message<p><br>
  </div>

    <div class="new_message_form">
      <%= form_with url: '/messages/create', method: :post, local: :true do |form| %>
          <%=form.text_field :message %><br><br>
          <%=form.submit "Send Message"%>
          <%= form.hidden_field :lat, :value => @lat %>
          <%= form.hidden_field :long, :value => @long %>
          <%= form.hidden_field :sat_id, :value => @sat_id %>
      <% end %>
    </div>
</div>

</body>
</html>

app/views/messages/show.html.erb
<!DOCTYPE html>
<html lang ="en">
<head>
  <title>Messages from the Stars</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <%= render partial: "shared/nav-hamburger" %>
</head>
<body>

<div class="bg_view_message">
    <% if @message != 404 %>

  <div class="view_message_header">
    <p>Intercepted Message</p>
  </div>

  <div class="view_message_body">
      <div class ="content">
      <div id="message-content">
        <p>Message:</p> 
        <p><%=@message.content%></p>
      </div>
      </div>
  </div>

  <div class="view_sub_body">
      <div id ="sat-name">
        Satellite Name: <%=@satellite.name%>
      </div>

      <div id="norad_id">
        Norad ID: <%=@satellite.norad_id%>
      </div>
      
      <div id="message-launch-date">
        Message Launched: <%=@message.formatted_creation_date%>
      </div>

      <div id="message-travel-time">
        Message has been traveling for <%=@message.travel_time_days%> days.
      </div>

      <div id="message-orbits">
        <p>This message has orbited around the world about <%=@message.orbit_count%> times,</p>
        <p>or around <%=@message.miles_traveled%> miles!</p>
      </div>
    <div class="lat_wrap"> 
    <div class="start">
      <div id="start-lat">
        Start Lat: <%=@message.start_lat%>
      </div>

      <div id="start-lng">
        Start Lng: <%=@message.start_lng%>
      </div>
    </div>

    <div class="message_map">
      <div id="map">
        <%=image_tag(@map_url)%>
      </div>
    </div>
    
    <div class="current">
      <div id="current-lat">
        Current Lat: <%=@satellite.sat_lat%>
      </div>

      <div id="current-lng">
        Current Lng: <%=@satellite.sat_lng%>
      </div>
    </div>
    </div>

  </div>
</div> 
    <% else %>
      <p> You broke the space-time continuum and your message disappeared into the void </p>
    <% end %>
    </div>
  </div> 
</body>
</html>

app/views/satellites/show.html.erb
<!DOCTYPE html>
<html lang ="en">
<head>
  <title>Message from the Stars</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <script>
    function myFunction() {
      var popup = document.getElementById("myPopup");
      popup.classList.toggle("show");
    }
  </script>
  <%= render partial: "shared/nav-hamburger" %>
</head>
<body>

<div class="bg_satshow">
    <% if @satellite != 404 %>
      <div class="satshow_header">
        <p>Satellite <%= @satellite.name %></p>
      <div class="satpop_container">
        <p>NORAD ID <%= @satellite.norad_id %></p>
        <div class="popup" onclick="myFunction()">What's a NORAD ID?
          <span class="popuptext" id="myPopup">NORAD is the North American Aeropsace Defense Command, an organization that provides aerospace warning, air sovereignty & protection to Canada & the U.S. The NORAD ID refers to the catalog number (known as the Satellite Catalog Number -SATCAT-) that is assigned by a differnet organization, the U.S. Space Command.</span>
        </div> 
      </div> 
      </div>
  


  <div class="vis_container">
      <div class="satshow_button">
      <div class="button">
        <%= button_to "Cast a New Message", "/messages/new", params: {:sat_id => @sat_id}, method: :get, local: true %>
        </div>
      </div>
  </div>  

    <div class="satshow_container satshow_center">

        <div class="sat_headers">
          <p>Visibility in the next 10 days</p>
        </div>

          <p class="text-center"> (Hover over date to view forecast)</p>
          <% if @visibility != nil %>
            <% @visibility[0..9].each_with_index do |v, idx| %>
                  <div id="visibility<%= idx%>">
                    <div class="sat_dropdown">
                      <p><%= v.starting_time %></p>
                      <% @weather_forecasts.each do |forecast| %>
                        <% if v.starting_time.include?(forecast.date)%>
                            <div class="satdropdown-content">
                              <p>Weather Forecast: <%= forecast.status %> </p>
                            </div>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
            <% end %>
          <% end %>

    </div>

      <div class="satshow_container">
          <div class="sat_headers">
            <p class="text-center">Current Location</p>
          </div>
          <p class="text-center">Latitude: <%= @satellite.sat_lat %>, Longitude: <%= @satellite.sat_lng %></p>
          <%=image_tag(@map_url)%>
      </div>

    <div class="satshow_container">
      <div class="sat_headers">
        <p> <%= @messages.size %> Total Messages </p>
      </div>
        <% @messages.each_with_index do |m, idx| %>
          <div id="messages<%= idx %>">
            <div class="col-md-6">
                <p>Message <%= link_to m.id, "/messages/#{m.id}" %></p>
            </div> 
        <% end %>
          </div>
      </div>

  <% else %>
    <h3> Oh no! Your satellite is lost is space. Try to find a different one.</h3>
  <% end %>
</div>    
</body>
</html>

app/views/shared/_nav-hamburger.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-left">
      <a class="navbar-brand" href="/"> Messages from the Stars</a>
        <li><a href="/users/dashboard"><span class="glyphicon glyphicon-user"></span> Control Center</a></li>
        <li><a href="/users/discover"><span class="glyphicon glyphicon-globe"></span> Scan the Skies</a></li>
        <li><a href="/about"><span class="glyphicon glyphicon-education"></span> About Page</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang ="en">
<head>
  <title>Message from the Stars</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <%= render partial: "shared/nav-hamburger" %>
</head>
<body>
<div class="bg_dashboard">
    <p class="py-5 text-center"></p>

    <div class="dashboard_header">
        <p>CONTROL CENTER</p>

    <div class="dashboard_container_body">
        <p>Click on a satellite to view details<p>
        <p>Click 'Scan the Skies' to interact with satellites above you<p>
    </div>

    <div class="dashboard_container_subheader">
        <p>Tracked Satellites</p>
    </div>
    </div>

    <%# <div class="text-center"> %>
        <%# <p><%= link_to 'Discover Satellites', discover_users_path, class: 'link_disc'</p><br> %>
    <%# </div> %>

        <% if @satellites %>
        <div id="satellites">
        <% @satellites.each do |s| %>
            <div class="satellite">

        <div class="col-md-4">
            <p>Norad Id: <%= s.norad_id %> </p> 
            <div class="button">
            <%= button_to "View This Satellite's Info", '/satellite', params: {:sat_id => s.norad_id}, method: :get, local: true %>
            </div>
            <% msg_collector = [] %>
            <% if @message_count != nil %>
                <% @message_count.each do |msg| %>
                    <% if msg.satellite_id == s.id.to_i %>
                        <% msg_collector << msg %>
                    <% end %>
                <% end %>
            <% end %>
            <p><%= msg_collector.count %> Messages<p>
            <%# <h4>Visibility in the next 7 days</h4>
            <% @visible_times[0..9].each do |vis_time| %>
            <%# <div class="col-sm-4">
                <% if s.id == vis_time.sat_id %>
                    <%# <p><%= vis_time.starting_time</p> %>
                    <%# <% @weather_forecasts.each do |forecast| %>
                        <%# <% if vis_time.starting_time.include?(forecast.date) %>
                            <%# <p>Weather: <%= forecast.status </p>  %>
                        <%# <% end %> 
                    <%# <% end %> 
                <%# <% end %> 
            <%# </div> %> 
            <%# <% end %> 
        </div>
        <% end %>
    <% end %>
            </div>                 
    </div>
</div>
</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang ="en">
<head>
  <title>Messages from the Stars</title>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="bg_landing">
  <div class="logo">
    <div class="landing_header">
      <p class="text_formating">MESSAGES</p>
    </div>
    <div class="landing_subheader">
      <p class="text_formating">FROM </p>
      <p class="text_formating">THE</p>
    </div>
    <div class="landing_stars">
      <p class="text_formating">STARS</p>
    </div>
  </div>

    <div class="landing_container_body text_formating">
      <p class="text_formating">Catch a satellite</p>
      <p class="text_formating">Create a message</p>
      <p class="text_formating">Cast your message into the cosmic ocean</p>
      <p class="text_formating">Log in to begin exploring the skies</p>
    </div>
    <div class="landing_container_login">
      <p><%= link_to 'Log In', '/auth/google_oauth2', class: 'link_text' %></p>
    </div>
</div>
</body>
</html>